import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "./components/navbar";
import Footer from "./components/footer";
import ImagesContainer from "./components/imagesContainer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="bg-whiteBg">
      <body className={inter.className}>
        <NavBar />
        <ImagesContainer />
        <main className="container mx-auto pt-4 min-h-screen">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
